---
- name: Check Topology Integration Process Status
  shell: ps axu|grep prepare_topology_objects.py|grep -v grep|wc -l
  register: ps_status
  tags:
    - start_topology_integration
    - stop_topology_integration
    - check_topology_integration

- name: Start Topology Integration
  shell: python "{{ remote_topology_integrate_executor }}" --modelfile="{{ remote_topology_model_file }}" --mrbtscount="{{ mrbts_count }}" --thread=4
  when:  ps_status.stdout == "0"
  tags:
    - start_topology_integration


- name: Stop Topology Integration
  shell: ps axu|grep prepare_topology_objects.py|grep -v grep|xargs kill -9
  when:  ps_status.stdout != "0"
  ignore_errors: yes
  tags:
    - stop_topology_integration


- debug:
    msg: "topology integration simulator is not started"
  when:  ps_status.stdout == "0"
  changed_when: false
  tags:
    - check_topology_integration

- name: Check Topology Integration Log
  shell: tail -n 10 "{{ remote_topology_integrate_log }}"
  when:  ps_status.stdout != "0"
  register: tail_result
  changed_when: false
  tags:
    - check_topology_integration

- debug:
    msg: "{{ tail_result.stdout_lines }}"
  when:  ps_status.stdout != "0"
  changed_when: false
  tags:
    - check_topology_integration