---
- name: Check FM Notification Process Status
  shell: ps axu|grep alarm_soap_simulator.py|grep -v grep|wc -l
  register: ps_status
  tags:
    - start_sender
    - start_fm_sender
    - stop_sender
    - stop_fm_sender
    - check
    - check_fm_sender
    - check_sender

- name: Start FM Notification Sender
  shell: python "{{ remote_alarm_notification_executor }}" --thread=10 --constant="{{ (alarm_constant / 3) | int }}" --burst="{{ (alarm_burst / 3) | int }}" --peak="{{ (alarm_peak / 3) | int }}"
  when:  ps_status.stdout == "0"
  tags:
    - start_sender
    - start_fm_sender


- name: Stop FM Notification Process
  shell: ps axu|grep alarm_soap_simulator.py|grep -v grep|xargs kill -9
  when:  ps_status.stdout != "0"
  ignore_errors: yes
  tags:
    - stop_sender
    - stop_fm_sender


- debug:
    msg: "alarm simulator is not started"
  when:  ps_status.stdout == "0"
  changed_when: false
  tags:
    - check
    - check_fm_sender
    - check_sender

- name: Check FM Notification Log
  shell: tail -n 10 "{{ remote_alarm_notification_log }}"
  when:  ps_status.stdout != "0"
  register: tail_result
  changed_when: false
  tags:
    - check
    - check_fm_sender
    - check_sender

- debug:
    msg: "{{ tail_result.stdout_lines }}"
  when:  ps_status.stdout != "0"
  changed_when: false
  tags:
    - check
    - check_fm_sender
    - check_sender